world:
    - id: walls
      shape:
        heightmap:
          image: $(file room1.pgm)
          height: 2
          resolution: 0.05
          pose: { x: -12.2, y: -12.2, z: 0 }

plugins:
    - name: gui_server
      lib: libed_gui_server_plugin.so
    - name: localization
      lib: libed_localization_plugin.so
      parameters:
        robot_name: robot
        initial_pose_topic: /initialpose
        initial_pose:
          x: 0
          y: 0
          rz: 0
        num_particles: 500 
        laser_model:
          topic: /scan
          num_beams: 30 # it was 100
          z_hit: 0.6   
          sigma_hit: 0.2
          z_short: 0.05  
          z_max: 0.05   
          z_rand: 0.4 
          lambda_short: 0.1
          range_max: 10
          min_particle_distance: 0.01
          min_particle_rotation_distance: 0.02
        odom_model:
          map_frame: map
          odom_frame: /odom
          base_link_frame: /base_footprint
          alpha1: 0.2  
          alpha2: 0.2  
          alpha3: 0.2  
          alpha4: 0.2  
          alpha5: 0.2 
    - name: laser_integration
      lib: libed_laser_plugin.so
      frequency: 40
      parameters:
        laser_topic: /scan
        min_segment_size_pixels: 8
        world_association_distance: 0.4
        segment_depth_threshold: 0.2
        min_cluster_size: 0.1
        max_cluster_size: 1.5
        max_gap_size: 10
    - name: entity_clearer
      lib: libed_clearer_plugin.so
      enabled: 1
      parameters:
        entity_timeout: 1.0
    - name: rgbd_integration
      lib: libed_kinect_plugin.so
      enabled: 1
      parameters:
        topic: /camera
    - name: navigation
      lib: libed_navigation_plugin.so
      parameters:
        occupancy_grid_publisher:
          resolution: 0.05    
          frame_id: /map      
          min_z: 0.01        
          max_z: 2.0          
          default_offset: 0.7 
